// <auto-generated />
namespace IMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class EditedStockPurchase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditedStockPurchase));
        
        string IMigrationMetadata.Id
        {
            get { return "201706211342412_EditedStockPurchase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
